project_id: "my-project-id"
stage: "test"
auth_provider_jwks_url: "https://example.com/jwks.json"
data_access_role_arn: "arn:aws:iam::123456789012:role/my-role"
db_instance_type: "t3.micro"
db_allocated_storage: 5
public_db_subnet: false
nat_gateway_count: 1
bastion_host_create_elastic_ip: false
bastion_host_allow_ip_list:
  - "192.0.2.0/32"
  - "203.0.113.0/32"
bastion_host_user_data:
  users:
    - name: USERNAME 
      shell: /bin/bash
      ssh_authorized_keys:
        - PUBLIC_SSH_KEY 
titiler_buckets:
  - "bucket1"
  - "bucket2"
